package de.heins.vokabeltraineronline.business.entity;

public enum BehaviourIfWrong {
	STAY_SUCCESSSTEP_NEXTDAY_TOMORROW //
	, STAY_SUCCESSSTEP_NEXTDAY_SUCCESSSTEP_DURATION //
	, PREVIOUS_SUCCESSTEP_NEXTDAY_TOMORROW //
	, PREVIOUS_SUCCESSSTEP_NEXTDAY_SUCCESSSTEP_DURATION

}
